[book]
authors = ["b1tg"]
language = "en"
multilingual = false
src = "src"

[output.html.playground]
editable = true
#copy-js = true
#line-numbers = true
[output.html]
additional-css = ["custom.css"]
